// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ProposalFactory$Type } from "./ProposalFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ProposalFactory"]: ProposalFactory$Type;
    ["contracts/futarchy/factory/ProposalFactory.sol:ProposalFactory"]: ProposalFactory$Type;
  }

  interface ContractTypesMap {
    ["ProposalFactory"]: GetContractReturnType<ProposalFactory$Type["abi"]>;
    ["contracts/futarchy/factory/ProposalFactory.sol:ProposalFactory"]: GetContractReturnType<ProposalFactory$Type["abi"]>;
  }
}
