// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Exchange$Type } from "./Exchange";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Exchange"]: Exchange$Type;
    ["contracts/futarchy/Exchange.sol:Exchange"]: Exchange$Type;
  }

  interface ContractTypesMap {
    ["Exchange"]: GetContractReturnType<Exchange$Type["abi"]>;
    ["contracts/futarchy/Exchange.sol:Exchange"]: GetContractReturnType<Exchange$Type["abi"]>;
  }
}
