// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CollateralMock$Type } from "./CollateralMock";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CollateralMock"]: CollateralMock$Type;
    ["contracts/futarchy/CollateralMock.sol:CollateralMock"]: CollateralMock$Type;
  }

  interface ContractTypesMap {
    ["CollateralMock"]: GetContractReturnType<CollateralMock$Type["abi"]>;
    ["contracts/futarchy/CollateralMock.sol:CollateralMock"]: GetContractReturnType<CollateralMock$Type["abi"]>;
  }
}
