// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TargetV2$Type } from "./TargetV2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TargetV2"]: TargetV2$Type;
    ["contracts/_sample/TargetV2.sol:TargetV2"]: TargetV2$Type;
  }

  interface ContractTypesMap {
    ["TargetV2"]: GetContractReturnType<TargetV2$Type["abi"]>;
    ["contracts/_sample/TargetV2.sol:TargetV2"]: GetContractReturnType<TargetV2$Type["abi"]>;
  }
}
