// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TargetV1$Type } from "./TargetV1";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TargetV1"]: TargetV1$Type;
    ["contracts/_sample/TargetV1.sol:TargetV1"]: TargetV1$Type;
  }

  interface ContractTypesMap {
    ["TargetV1"]: GetContractReturnType<TargetV1$Type["abi"]>;
    ["contracts/_sample/TargetV1.sol:TargetV1"]: GetContractReturnType<TargetV1$Type["abi"]>;
  }
}
