// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Comparators$Type } from "./Comparators";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Comparators"]: Comparators$Type;
    ["@openzeppelin/contracts/utils/Comparators.sol:Comparators"]: Comparators$Type;
  }

  interface ContractTypesMap {
    ["Comparators"]: GetContractReturnType<Comparators$Type["abi"]>;
    ["@openzeppelin/contracts/utils/Comparators.sol:Comparators"]: GetContractReturnType<Comparators$Type["abi"]>;
  }
}
