// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Factory$Type } from "./Factory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Factory"]: Factory$Type;
    ["contracts/_sample/Factory.sol:Factory"]: Factory$Type;
  }

  interface ContractTypesMap {
    ["Factory"]: GetContractReturnType<Factory$Type["abi"]>;
    ["contracts/_sample/Factory.sol:Factory"]: GetContractReturnType<Factory$Type["abi"]>;
  }
}
