// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Clones$Type } from "./Clones";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Clones"]: Clones$Type;
    ["@openzeppelin/contracts/proxy/Clones.sol:Clones"]: Clones$Type;
  }

  interface ContractTypesMap {
    ["Clones"]: GetContractReturnType<Clones$Type["abi"]>;
    ["@openzeppelin/contracts/proxy/Clones.sol:Clones"]: GetContractReturnType<Clones$Type["abi"]>;
  }
}
